### ISSUE TITLE
newProject event - add owner

### ISSUE THREAD

**Issue by evvvritt** [radicle-dev/funding-contracts#16]
Please add owner to newProject event so when listening you can determine if project is related to the user that just created one :)

EDIT: and add `ipfsHash` for graph?

**Comment by CodeSandwich** [comment]
Isn't the project owner already emitted in `NewProject`? https://github.com/radicle-dev/funding-contracts/blob/master/src/registry.sol#L23 Or do you mean something else?

**Comment by evvvritt** [comment]
Ah yes sorry, wasn't pulling it in as second argument.
